-- ****************************** SCRIPT DE CRIAÇÂO DA ESTRUTURA DO BANCO DE DADOS USADO NO SISTEMA *****************************************

-- CRIANDO SCHEMA:
CREATE SCHEMA IF NOT EXISTS `DADOS_PETSHOP`;

-- ************************** TABELAS ****************************

-- ** TABELA 'TIPO_DE_USUARIO' ** :
CREATE TABLE TIPO_DE_USUARIO(
ID_DO_TIPO INT NOT NULL PRIMARY KEY,
NOME_DO_TIPO VARCHAR(20) NOT NULL
);


-- ** TABELA 'USUARIO' ** :
CREATE TABLE USUARIO(
ID_USUARIO INT NOT NULL,
USERNAME CHAR(20) NOT NULL,
NOME VARCHAR(30) NOT NULL,
SOBRENOME VARCHAR(30) NOT NULL,
NOME_COMPLETO VARCHAR(100),
DATA_DE_NASCIMENTO DATE NOT NULL,
IDADE INTEGER,
SEXO CHAR(1) NOT NULL,
TIPO_DE_USUARIO INT NOT NULL,
SENHA CHAR(14) NOT NULL,

-- CHAVES:
PRIMARY KEY(ID_USUARIO),
CONSTRAINT CHAVE_USUARIO_PARA_TIPO_DE_USUARIO FOREIGN KEY(TIPO_DE_USUARIO) REFERENCES TIPO_DE_USUARIO(ID_DO_TIPO)
);

-- CRIANDO TRIGGER QUE POPULA A COLUNA 'NOME_COMPLETO' DE ACORDO COM O VALOR DE 'NOME' E 'SOBRENOME' INSERIDOS:
DELIMITER $$ 

CREATE TRIGGER POPULAR_NOME_COMPLETO_USUARIO
BEFORE INSERT ON USUARIO 
FOR EACH ROW 
BEGIN 
	SET NEW.NOME_COMPLETO = CONCAT(NEW.NOME, ' ', NEW.SOBRENOME);
END $$

DELIMITER ;

-- CRIANDO TRIGGER QUE POPULA O CAMPO 'IDADE' DE ACORDO COM O VALOR PASSADO EM 'DATA_DE_NASCIMENTO':
DELIMITER $$
CREATE TRIGGER POPULAR_IDADE_USUARIO
BEFORE INSERT ON USUARIO
FOR EACH ROW

BEGIN
	SET NEW.IDADE = TIMESTAMPDIFF(YEAR, NEW.DATA_DE_NASCIMENTO, CURDATE());
END $$

DELIMITER ;







