-- ************ IMPLEMENTANDO STORES PROCEDURES ************:

-- PROCEDURE QUE OBTÉM A SOMA DOS VALORES DE PRODUTOS COMPRADOS POR DETERMINADO CLIENTE QUE SERÁ PASSADO POR PARÂMETRO:
DELIMITER $$
CREATE PROCEDURE OBTER_GASTOS_COM_PRODUTOS(IN ID_DO_CLIENTE INT)
BEGIN
	-- VARIÁVEL QUE ARMAZENARÁ O VALOR DAS SOMAS:
    DECLARE SOMA_DOS_GASTOS DECIMAL(10, 2);
	
    -- OBTENDO A SOMA DOS VALORES:
    SELECT SUM(VALOR_DA_VENDA) INTO SOMA_DOS_GASTOS
    FROM VENDA_FEITA
    WHERE CLIENTE_COMPRADOR = ID_DO_CLIENTE;
    
    -- EXIBINDO VALORES:
	SELECT SOMA_DOS_GASTOS;
END $$

DELIMITER ;